# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r3MaFRWDfbircakdee18V1Q5PaJuVGCA
"""

!pip install twython
from twython import Twython

consumer_key        = '3rJOl1ODzm9yZy63FACdg'
consumer_secret     = '5jPoQ5kQvMJFDYRNE8bQ4rHuds4xJqhvgNJM4awaE8'
access_token        = '1936951807-z5bBNING8P1TU2onWvJh5dh8hoYlYAmNOaAx2OX'
access_token_secret = 'QWJEZ7ridSeZGdxJELSBk7mupCpMA9q9sLCou5ywg'

twitter = Twython (
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)
message = "stay happy"
image = open('jatin.png', 'rb')
response = twitter.upload_media(media=image)
media_id = [response['media_id']]
twitter.update_status(status=message, media_ids=media_id)

from twython import TwythonStreamer

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            print(data['text'])
stream = MyStreamer(
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)
stream.statuses.filter(track='London')

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            username = data['user']['screen_name']
            tweet = data['text']
            print("@{}: {}".format(username, tweet))